---
- name: Manage Google Cloud Resources
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create network
      google.cloud.gcp_compute_network:
        name: my-vpc-network
        auto_create_subnetworks: false
        auth_kind: serviceaccount
        service_account_file: /mnt/c/Users/roman/Desktop/Credentials/cred2.json
        project: mydevopsproject-395211
      register: network_result

    - name: Create subnetwork
      google.cloud.gcp_compute_subnetwork:
        name: my-subnet
        network: "{{ my-vpc-network }}"
        ip_cidr_range: "10.0.0.0/24"
        region: europe-west1
        auth_kind: serviceaccount
        service_account_file: /mnt/c/Users/roman/Desktop/Credentials/cred2.json
        project: mydevopsproject-395211

    - name: Create firewall rule
      google.cloud.gcp_compute_firewall:
        name: allow-http
        network: "{{ my-vpc-network }}"
        allowed:
          - protocol: tcp
            ports:
              - "80"
        source_ranges:
          - "0.0.0.0/0"
        auth_kind: serviceaccount
        service_account_file: /mnt/c/Users/roman/Desktop/Credentials/cred2.json
        project: mydevopsproject-395211
