---
- name: Deploy your-app on Kubernetes
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Build Docker image
      shell: docker build -t wildrydes-webapp:latest /mnt/c/Users/roman/Desktop/InternshipProject/wildrydes-site

    - name: Authenticate with Google Cloud Registry
      shell: gcloud auth configure-docker --quiet

    - name: Tag Docker image
      shell: docker tag wildrydes-webapp:latest gcr.io/mydevopsproject-395211/wildrydes-webapp:latest

    - name: Push Docker image to Google Cloud Registry
      shell: docker push gcr.io/mydevopsproject-395211/wildrydes-webapp:latest

    - name: Apply Kubernetes Deployment
      shell: kubectl create deployment wildrydes--site-deployment --image=gcr.io/mydevopsproject-395211/wildrydes-webapp:latest

    - name: Apply Kubernetes HPA
      shell: kubectl autoscale deployment wildrydes--site-deployment --cpu-percent=70 --min=2 --max=5
