apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: wildrydes--site-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 
  type: LoadBalancer
